### ISSUE TITLE
Wo hängst du bei Teil3?

### ISSUE THREAD

**Issue by suchja** [20Marco20/TicTacToe#1]
@20Marco20 Ich habe mir gerade deinen Code angeschaut. Das sieht doch erstmal nicht schlecht aus. Bei welcher Teilaufgabe bist du gerade und was will nicht klappen?

**Comment by 20Marco20** [comment]
z.B. wäre ist meine Überlegung: Spieler 1 + 2 anzulegen. Aber woher weiß denn der PC, welches Zeichen als letztes gespeichert wurde?

**Comment by suchja** [comment]
Da musst du dir im Quellcode merken welches Zeichen als letztes gesetzt wurde. Dazu kannst du dir in der Klasse `MainWindow` ein Attribut anlegen. Du könntest das zum Beispiel so machen:

```csharp
private bool _istErsterSpielerAmZug = true;
```

Wenn der erste Spieler seinen Spielstein gesetzt hat, dann ist der erste Spieler nicht mehr am Zug. Du kannst dem Attribut also `false` zuweisen. Das würde ich im EventHandler machen. Dort kannst du dieses Attribut auch abfragen.

Die ganzen Zusammenhänge und Begriffe wie Objekte, Klasse, Attribute, Methoden, ... erkläre ich in dieser [YouTube-Playlist über ObjektOrientierung](https://www.youtube.com/playlist?list=PLP2TrPpx5VNl4t9kS2MMWNveEWl41gEKX) und einen geführten Einstieg in die C# Grundlagen bekommst du in meinem Online-Kurs ["Einstieg in C#"](https://www.lernmoment.de/einstieg-csharp/).

Hilft dir das etwas weiter?

**Comment by 20Marco20** [comment]
ich probiere und melde mich

**Comment by 20Marco20** [comment]
juhu. Das hat schon mal funktioniert (bei Gut hochgeladen).
Jetzt zum nächsten Schritt.
