### ISSUE TITLE
Methode private bool IstSpielfeldVoll() bring Fehler

### ISSUE THREAD

**Issue by 20Marco20** [20Marco20/TicTacToe#2]
Wenn ich das Spiel starte kommt System.NullReferenceException.

In dieser Zeile ist das B unterstrichen:
Button kaestchen = item as Button;

Was mache ich falsch?

**Comment by 20Marco20** [comment]
Habe es geschafft. Habe "Content" eingefügt.


```
        private bool IstSpielfeldVoll()
        {
            foreach (var item in Spielfeld.Children)
            {
                Button b = item as Button;

                if (b.Content == null || b.Content.ToString() == string.Empty)
                {
                    return false;
                }
            }
            return true;
        }
```


Ob das nun stimmt? Es geht jedenfalls.

**Comment by suchja** [comment]
Na das sieht doch super aus. Das Problem mit der `NullReferenceException` war, dass einige der `Button` zum Spielstart noch keinen Inhalt hatten. Damit war `Content == null` lässt du in der Überprüfung als das `b.Content == null` weg und machst nur `b.Content.ToString()` versucht die Anwendung zur Laufzeit auf `b.Content` die Methode `ToString()` aufzurufen. Das geht aber nicht, weil halt `Content == null`. Darum wird dann die `NullReferenceException` geschmissen.

Dies wird auch kein Problem mehr, wenn du zu Spielstart alle `Button` beispielsweise mit einem `string.empty` auf einen Standardwert setzt. Das kommt dann in einer der nächsten Übungen.

Außerdem sehe ich in deiner `IstSpielfeldVoll()` Methode noch ein potentielles Risiko. Wenn du magst, dann kannst du nochmals den [Artikel über den `Cast`](https://www.lernmoment.de/csharp-tutorial-deutsch/typkonvertierung-mit-cast/) lesen. Was wird passieren, wenn in `Spielfeld.Children` nicht nur `Button` enthalten sind, sondern vielleicht auch ein `Label`?
